// Code generated by tools/catgen from catalog/catalog.yaml. DO NOT EDIT.

// Inductance.
package inductance

import (
	"github.com/timzifer/metrology"
	"github.com/timzifer/metrology/dimension"
	"github.com/timzifer/metrology/symbol"
)

// dim is the dimension every unit in this package measures.
var dim = dimension.New(dimension.Exponents{Time: -2, Length: 2, Mass: 1, ElectricCurrent: -2})

// Henry is the SI unit of inductance, Wb·A⁻¹.
//
// Source: SI Brochure 9th ed., §2.3.4 Table 4
var Henry = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Symbol:    symbol.SI("H"),
})
