package main

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strings"
)

// header is the line that keeps generated files out of the coverage figure and
// out of anyone's editor. The wording is the convention from
// https://go.dev/s/generatedcode; covercheck matches it exactly (D14).
const header = "// Code generated by tools/catgen from the catalogue in catalog/. DO NOT EDIT."

// emitQuantity writes the package for one quantity.
func emitQuantity(module string, q quantity, byID map[string]unitSpec) ([]byte, error) {
	var b bytes.Buffer

	fmt.Fprintln(&b, header)
	fmt.Fprintln(&b)
	writeDoc(&b, q.Doc, "")
	fmt.Fprintf(&b, "package %s\n\n", q.Package)

	imports := []string{
		fmt.Sprintf("%q", module),
		fmt.Sprintf("%q", module+"/dimension"),
		fmt.Sprintf("%q", module+"/symbol"),
	}
	for _, u := range q.Units {
		if u.Interval == "" {
			continue
		}
		target := byID[u.Interval]
		if target.quantity.Package != q.Package {
			imports = append(imports, fmt.Sprintf("%q", target.quantity.importPath(module)))
		}
	}
	imports = unique(imports)
	fmt.Fprintf(&b, "import (\n%s\n)\n\n", strings.Join(imports, "\n"))

	// The dimension is written once per package rather than once per unit:
	// every unit of a quantity has the same one, and repeating it would be a
	// place for the two to drift apart. A provenance package has no one
	// dimension to write, so every unit there carries its own (D19).
	if !q.isProvenance() {
		fmt.Fprintf(&b, "// dim is the dimension every unit in this package measures.\nvar dim = %s\n\n",
			q.Dimension.dimensionExpr())
	}

	// The tag is a reserved name of this catalogue (D16), so it is declared
	// once, here, rather than spelled as a string literal at every call site
	// that compares against it. The unit definitions below take it from this
	// same constant: one spelling per package, and nothing to drift.
	if q.Quantity != "" {
		fmt.Fprintf(&b, `// Quantity is what every unit in this package measures, where the
// dimension alone does not say it: %s.
//
// It is a reserved name of this catalogue (D6, D16) and the spelling a caller
// should compare against — a string literal of the same words is a second
// spelling of one fact, with nothing to keep the two in step.
const Quantity metrology.Quantity = %q

`, q.Quantity, q.Quantity)
	}

	for _, u := range q.Units {
		// Take the resolved spec: the one hanging off the quantity knows which
		// package it belongs to, the one in the YAML struct does not.
		if err := emitUnit(&b, byID[u.ID], q, byID); err != nil {
			return nil, err
		}
	}

	return format.Source(b.Bytes())
}

// emitUnit writes one unit definition.
func emitUnit(b *bytes.Buffer, u unitSpec, q quantity, byID map[string]unitSpec) error {
	symbolExpr, err := u.Symbol.symbolExpr()
	if err != nil {
		return fmt.Errorf("unit %s: %w", u.ID, err)
	}

	doc := u.Doc
	if doc == "" {
		doc = u.Symbol.text()
	}
	fmt.Fprintf(b, "// %s is %s.\n//\n// Source: %s\n", u.Go, doc, u.Source)

	fmt.Fprintf(b, "var %s = metrology.MustUnit(metrology.UnitDef{\n", u.Go)
	if q.isProvenance() {
		fmt.Fprintf(b, "Dimension: %s,\n", u.dimension().dimensionExpr())
	} else {
		fmt.Fprintln(b, "Dimension: dim,")
	}
	if u.isAbsolute() {
		fmt.Fprintf(b, "Kind: %s,\n", u.kindExpr())
	}
	if u.quantityTag() != "" {
		// The constant this package declares, not the same words again (D16).
		fmt.Fprint(b, "Quantity: Quantity,\n")
	}
	fmt.Fprintf(b, "Symbol: %s,\n", symbolExpr)
	if u.Factor.Num != "" {
		fmt.Fprintf(b, "Numerator: %q,\n", u.Factor.Num)
	}
	if u.Factor.Den != "" {
		fmt.Fprintf(b, "Denominator: %q,\n", u.Factor.Den)
	}
	if u.Offset != "" {
		fmt.Fprintf(b, "Offset: %q,\n", u.Offset)
	}
	if u.Interval != "" {
		target := byID[u.Interval]
		reference := "&" + target.Go
		if target.quantity.Package != q.Package {
			reference = "&" + target.qualified()
		}
		fmt.Fprintf(b, "Interval: %s,\n", reference)
	}
	fmt.Fprint(b, "})\n\n")
	return nil
}

// emitIndex writes the catalogue package's data: every unit, the canonical unit
// per dimension and kind, and the symbol index.
//
// It is data only. The lookups around it are hand-written in catalog.go, so
// that the code with behaviour in it is the code the coverage gate measures.
func emitIndex(module string, c *catalogue) ([]byte, error) {
	var b bytes.Buffer

	fmt.Fprintln(&b, header)
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "package catalog")
	fmt.Fprintln(&b)

	units := c.units()
	imports := []string{fmt.Sprintf("%q", module)}
	for _, u := range units {
		imports = append(imports, fmt.Sprintf("%q", u.quantity.importPath(module)))
	}
	fmt.Fprintf(&b, "import (\n%s\n)\n\n", strings.Join(unique(imports), "\n"))

	fmt.Fprintln(&b, "// all is every unit in the catalogue, ordered by catalogue id.")
	fmt.Fprintln(&b, "var all = []metrology.Unit{")
	for _, u := range units {
		fmt.Fprintf(&b, "%s, // %s\n", u.qualified(), u.ID)
	}
	fmt.Fprint(&b, "}\n\n")

	fmt.Fprintln(&b, "// canonical maps a dimension, kind and quantity to the unit a result")
	fmt.Fprintln(&b, "// computed into that dimension is expressed in.")
	fmt.Fprintln(&b, "var canonical = map[key]metrology.Unit{")
	for _, u := range units {
		if !u.Canonical {
			continue
		}
		fmt.Fprintf(&b, "{dim: %s.%s.Dimension(), kind: %s, quantity: %q}: %s,\n",
			u.quantity.Package, u.Go, u.kindExpr(), u.quantityTag(), u.qualified())
	}
	fmt.Fprint(&b, "}\n\n")

	fmt.Fprintln(&b, "// bySymbol resolves the printed form of a unit back to the unit.")
	fmt.Fprintln(&b, "var bySymbol = map[symbolKey]metrology.Unit{")
	for _, u := range units {
		fmt.Fprintf(&b, "{text: %q, kind: %s}: %s,\n", u.Symbol.text(), u.kindExpr(), u.qualified())
	}
	fmt.Fprint(&b, "}\n\n")

	return format.Source(b.Bytes())
}

// writeDoc renders a package comment, wrapping nothing and trusting the YAML.
func writeDoc(b *bytes.Buffer, doc, indent string) {
	if doc == "" {
		return
	}
	for _, line := range strings.Split(strings.TrimRight(doc, "\n"), "\n") {
		if line == "" {
			fmt.Fprintf(b, "%s//\n", indent)
			continue
		}
		fmt.Fprintf(b, "%s// %s\n", indent, line)
	}
}

// unique sorts and deduplicates import lines, so that the output does not
// depend on the order the catalogue happens to be written in.
func unique(values []string) []string {
	sort.Strings(values)
	out := values[:0]
	for i, v := range values {
		if i == 0 || values[i-1] != v {
			out = append(out, v)
		}
	}
	return out
}

// emitVetTable writes the dimension table the static checker of D13 resolves
// catalogue units against.
//
// It is generated from the same YAML as the library itself, which is the whole
// point: a checker with its own copy of the units would disagree with the
// runtime the first time a factor changed, and disagree silently. The table
// keys a unit variable by the name the checker sees in the SSA — the import
// path of its package and the identifier — and carries only what the checker
// compares: dimension, kind and quantity tag.
//
// Like the catalogue index it is data only. There is no generated branch in
// here for anyone to write a test for; the walk that reads it is hand-written
// in unitvet, where the coverage gate of D14 sees it.
func emitVetTable(module string, c *catalogue) ([]byte, error) {
	var b bytes.Buffer

	fmt.Fprintln(&b, header)
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "package unitvet")
	fmt.Fprintln(&b)

	// The metrology import is named only by the kind of an absolute unit, so a
	// catalogue without one must not declare it: gofmt keeps an unused import,
	// and the generated file would not compile.
	imports := []string{fmt.Sprintf("%q", module+"/dimension")}
	for _, u := range c.units() {
		if u.isAbsolute() {
			imports = append(imports, fmt.Sprintf("%q", module))
			break
		}
	}
	fmt.Fprintf(&b, "import (\n%s\n)\n\n", strings.Join(unique(imports), "\n"))

	fmt.Fprintln(&b, "// catalogue is every unit the library ships, keyed by the qualified name of")
	fmt.Fprintln(&b, "// the package-level variable holding it.")
	fmt.Fprintln(&b, "var catalogue = map[string]scale{")
	for _, u := range c.units() {
		fmt.Fprintf(&b, "%q: {dim: %s", u.quantity.importPath(module)+"."+u.Go, u.dimension().dimensionExpr())
		if u.isAbsolute() {
			fmt.Fprintf(&b, ", kind: %s", u.kindExpr())
		}
		if u.quantityTag() != "" {
			fmt.Fprintf(&b, ", quantity: %q", u.quantityTag())
		}
		fmt.Fprintf(&b, "}, // %s\n", u.ID)
	}
	fmt.Fprint(&b, "}\n\n")

	return format.Source(b.Bytes())
}
