// Code generated by tools/catgen from catalog/catalog.yaml. DO NOT EDIT.

// Magnetic flux density.
package fluxdensity

import (
	"github.com/timzifer/metrology"
	"github.com/timzifer/metrology/dimension"
	"github.com/timzifer/metrology/symbol"
)

// dim is the dimension every unit in this package measures.
var dim = dimension.New(dimension.Exponents{Time: -2, Mass: 1, ElectricCurrent: -1})

// Tesla is the SI unit of magnetic flux density, Wb·m⁻².
//
// Source: SI Brochure 9th ed., §2.3.4 Table 4
var Tesla = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Symbol:    symbol.SI("T"),
})

// Gauss is the CGS unit of magnetic flux density, a ten-thousandth of a tesla.
//
// Source: NIST SP 811 (2008), Appendix B.8
var Gauss = metrology.MustUnit(metrology.UnitDef{
	Dimension:   dim,
	Symbol:      symbol.Static("G"),
	Numerator:   "1",
	Denominator: "10000",
})
