// Code generated by tools/catgen from catalog/catalog.yaml. DO NOT EDIT.

// Illuminance, luminous flux per area.
package illuminance

import (
	"github.com/timzifer/metrology"
	"github.com/timzifer/metrology/dimension"
	"github.com/timzifer/metrology/symbol"
)

// dim is the dimension every unit in this package measures.
var dim = dimension.New(dimension.Exponents{Length: -2, LuminousIntensity: 1})

// Lux is the SI unit of illuminance, lm·m⁻².
//
// Source: SI Brochure 9th ed., §2.3.4 Table 4
var Lux = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Symbol:    symbol.SI("lx"),
})
