// Code generated by tools/catgen from the catalogue in catalog/. DO NOT EDIT.

// Capacitance, charge stored per volt.
package capacitance

import (
	"github.com/timzifer/metrology"
	"github.com/timzifer/metrology/dimension"
	"github.com/timzifer/metrology/symbol"
)

// dim is the dimension every unit in this package measures.
var dim = dimension.New(dimension.Exponents{Time: 4, Length: -2, Mass: -1, ElectricCurrent: 2})

// Farad is the SI unit of capacitance, C·V⁻¹.
//
// Source: SI Brochure 9th ed., §2.3.4 Table 4
var Farad = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Symbol:    symbol.SI("F"),
})
