// Code generated by tools/catgen from catalog/catalog.yaml. DO NOT EDIT.

// Volume, length cubed.
package volume

import (
	"github.com/timzifer/metrology"
	"github.com/timzifer/metrology/dimension"
	"github.com/timzifer/metrology/symbol"
)

// dim is the dimension every unit in this package measures.
var dim = dimension.New(dimension.Exponents{Length: 3})

// CubicMetre is the SI unit of volume.
//
// Source: SI Brochure 9th ed., §2.3.4 Table 3
var CubicMetre = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Symbol:    symbol.SIPow("m", 3),
})

// Litre is a thousandth of a cubic metre.
//
// Source: SI Brochure 9th ed., §4.1 Table 8
var Litre = metrology.MustUnit(metrology.UnitDef{
	Dimension:   dim,
	Symbol:      symbol.Litre(),
	Numerator:   "1",
	Denominator: "1000",
})
