// Code generated by tools/catgen from the catalogue in catalog/. DO NOT EDIT.

// Velocity, length per time.
package velocity

import (
	"github.com/timzifer/metrology"
	"github.com/timzifer/metrology/dimension"
	"github.com/timzifer/metrology/symbol"
)

// dim is the dimension every unit in this package measures.
var dim = dimension.New(dimension.Exponents{Time: -1, Length: 1})

// MetrePerSecond is the SI unit of velocity.
//
// Source: SI Brochure 9th ed., §2.3.4 Table 3
var MetrePerSecond = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Symbol:    symbol.Quotient(symbol.SI("m"), symbol.SI("s")),
})

// KilometrePerHour is a kilometre in an hour.
//
// Source: NIST SP 811 (2008), Appendix B.8
var KilometrePerHour = metrology.MustUnit(metrology.UnitDef{
	Dimension:   dim,
	Symbol:      symbol.Static("km/h"),
	Numerator:   "1",
	Denominator: "3.6",
})
