// Code generated by tools/catgen from catalog/catalog.yaml. DO NOT EDIT.

// Thermodynamic temperature as a point on a scale.
//
// Every unit here is absolute: 20 °C is a place, not a distance. Adding two
// of them is an error, and subtracting them yields an interval from the
// interval package (D6).
package temperature

import (
	"github.com/timzifer/metrology"
	"github.com/timzifer/metrology/dimension"
	"github.com/timzifer/metrology/symbol"
	"github.com/timzifer/metrology/units/interval"
)

// dim is the dimension every unit in this package measures.
var dim = dimension.New(dimension.Exponents{Temperature: 1})

// Kelvin is the SI base unit of thermodynamic temperature.
//
// Source: SI Brochure 9th ed., §2.3.1
var Kelvin = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Kind:      metrology.Absolute,
	Symbol:    symbol.SI("K"),
	Interval:  &interval.Kelvin,
})

// Celsius is the Celsius scale, offset from the kelvin by the ice point.
//
// Source: SI Brochure 9th ed., §2.3.4
var Celsius = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Kind:      metrology.Absolute,
	Symbol:    symbol.Static("°C"),
	Offset:    "273.15",
	Interval:  &interval.Kelvin,
})

// Fahrenheit is the Fahrenheit scale, five ninths of a kelvin per degree.
//
// Source: NIST SP 811 (2008), Appendix B.8
var Fahrenheit = metrology.MustUnit(metrology.UnitDef{
	Dimension:   dim,
	Kind:        metrology.Absolute,
	Symbol:      symbol.Static("°F"),
	Numerator:   "5",
	Denominator: "9",
	Offset:      "459.67",
	Interval:    &interval.Rankine,
})
