// Code generated by tools/catgen from the catalogue in catalog/. DO NOT EDIT.

// Package imperial holds the units of the imperial system that differ from
// the United States ones of the same name.
//
// Its counterpart is units/customary/us, and the units the two systems
// agree on are in the parent, units/customary (D19). As there, none of
// these carries the bare spelling: "gal" resolves to no unit in this
// catalogue, because it names two that are a fifth apart (O3).
package imperial

import (
	"github.com/timzifer/metrology"
	"github.com/timzifer/metrology/dimension"
	"github.com/timzifer/metrology/symbol"
)

// Gallon is the imperial gallon, exactly 4.54609 litres.
//
// Source: NIST SP 811 (2008), Appendix B.6
var Gallon = metrology.MustUnit(metrology.UnitDef{
	Dimension:   dimension.New(dimension.Exponents{Length: 3}),
	Symbol:      symbol.Static("galImp"),
	Numerator:   "454609",
	Denominator: "100000000",
})

// FluidOunce is a hundred-and-sixtieth of an imperial gallon.
//
// Source: NIST SP 811 (2008), Appendix B.6
var FluidOunce = metrology.MustUnit(metrology.UnitDef{
	Dimension:   dimension.New(dimension.Exponents{Length: 3}),
	Symbol:      symbol.Static("flozImp"),
	Numerator:   "454609",
	Denominator: "16000000000",
})

// Ton is the long ton, two thousand two hundred and forty pounds, exactly 1016.0469088 kilograms.
//
// Source: NIST SP 811 (2008), Appendix B.6
var Ton = metrology.MustUnit(metrology.UnitDef{
	Dimension:   dimension.New(dimension.Exponents{Mass: 1}),
	Symbol:      symbol.Static("tonImp"),
	Numerator:   "10160469088",
	Denominator: "10000000",
})
