// Code generated by tools/catgen from the catalogue in catalog/. DO NOT EDIT.

// Electric conductance, the reciprocal of resistance.
package conductance

import (
	"github.com/timzifer/metrology"
	"github.com/timzifer/metrology/dimension"
	"github.com/timzifer/metrology/symbol"
)

// dim is the dimension every unit in this package measures.
var dim = dimension.New(dimension.Exponents{Time: 3, Length: -2, Mass: -1, ElectricCurrent: 2})

// Siemens is the SI unit of electric conductance, A·V⁻¹.
//
// Source: SI Brochure 9th ed., §2.3.4 Table 4
var Siemens = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Symbol:    symbol.SI("S"),
})
