package main

import (
	"os"
	"path/filepath"
	"testing"
)

// D14 excludes generated files from both numerator and denominator, and M3 asks
// for that to be demonstrated rather than assumed: the catalogue is generated
// (D8), so from here on most of the line count in the repository is code nobody
// wrote and no test should be written for.
func TestGeneratedFilesAreExcluded(t *testing.T) {
	dir := t.TempDir()
	chdir(t, dir)

	write(t, filepath.Join(dir, "pressure", "pressure_gen.go"), `// Code generated by tools/catgen from catalog/catalog.yaml. DO NOT EDIT.

package pressure

var Bar = 1
`)
	write(t, filepath.Join(dir, "unit.go"), `package metrology

func half() int {
	return 1
}
`)

	blocks := []block{
		{file: "example.com/m/pressure/pressure_gen.go", startLine: 4, statements: 3, count: 0},
		{file: "example.com/m/unit.go", startLine: 3, statements: 1, count: 1},
	}

	kept, generated, excluded, ignored := filter(blocks, "example.com/m", []string{"cmd/", "tools/"})

	if generated != 3 {
		t.Errorf("generated statements excluded = %d, want 3", generated)
	}
	// filter strips the module prefix, so what remains is a repository path.
	if len(kept) != 1 || kept[0].file != "unit.go" {
		t.Fatalf("kept = %+v, want only the hand-written file", kept)
	}
	if excluded != 0 || ignored != 0 {
		t.Errorf("excluded = %d, ignored = %d, want 0 and 0", excluded, ignored)
	}
	// The generated file is uncovered, and coverage is still 100 %: that is the
	// point of the exclusion.
	if kept[0].count == 0 {
		t.Error("the hand-written block was reported uncovered")
	}
}

func TestPrefixesAreExcluded(t *testing.T) {
	dir := t.TempDir()
	chdir(t, dir)
	write(t, filepath.Join(dir, "tools", "catgen", "main.go"), "package main\n")

	blocks := []block{{file: "example.com/m/tools/catgen/main.go", statements: 7}}
	kept, _, excluded, _ := filter(blocks, "example.com/m", []string{"cmd/", "tools/"})
	if len(kept) != 0 {
		t.Errorf("kept = %+v, want nothing under tools/", kept)
	}
	if excluded != 7 {
		t.Errorf("excluded = %d, want 7", excluded)
	}
}

// A statement can be excused individually, but only with a reason attached —
// which is what makes the exception list in COVERAGE_EXCEPTIONS.md reviewable.
func TestIgnoredStatements(t *testing.T) {
	dir := t.TempDir()
	chdir(t, dir)
	write(t, filepath.Join(dir, "convert.go"), `package metrology

func convert() int {
	if impossible() { //coverage:ignore apd cannot fail on a finite decimal
		return 0
	}
	return 1
}
`)

	blocks := []block{
		{file: "example.com/m/convert.go", startLine: 4, statements: 1},
		{file: "example.com/m/convert.go", startLine: 7, statements: 1, count: 1},
	}
	kept, _, _, ignored := filter(blocks, "example.com/m", nil)
	if ignored != 1 {
		t.Errorf("ignored = %d, want 1", ignored)
	}
	if len(kept) != 1 || kept[0].startLine != 7 {
		t.Errorf("kept = %+v, want only the statement without the marker", kept)
	}
}

func TestMerge(t *testing.T) {
	// With -coverpkg=./... every test binary reports every block of every
	// package, so the same block arrives once per package: covered by the tests
	// of its own package, uncovered in all the others.
	blocks := []block{
		{file: "a.go", startLine: 1, statements: 2, count: 0},
		{file: "a.go", startLine: 1, statements: 2, count: 5},
		{file: "a.go", startLine: 9, statements: 1, count: 0},
	}
	merged := merge(blocks)
	if len(merged) != 2 {
		t.Fatalf("merged into %d blocks, want 2", len(merged))
	}
	if merged[0].count != 5 {
		t.Errorf("count = %d, want the counts summed", merged[0].count)
	}
	if merged[1].count != 0 {
		t.Errorf("an uncovered block became covered: %+v", merged[1])
	}
}

func TestParseProfile(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "coverage.out")
	write(t, path, "mode: atomic\nexample.com/m/unit.go:3.13,5.2 1 4\n")

	blocks, err := parseProfile(path)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(blocks) != 1 {
		t.Fatalf("got %d blocks, want 1", len(blocks))
	}
	got := blocks[0]
	if got.file != "example.com/m/unit.go" || got.startLine != 3 || got.endLine != 5 ||
		got.statements != 1 || got.count != 4 {
		t.Errorf("block = %+v", got)
	}

	t.Run("a malformed line is an error, not a silent zero", func(t *testing.T) {
		bad := filepath.Join(dir, "bad.out")
		write(t, bad, "mode: atomic\nthis is not a profile line\n")
		if _, err := parseProfile(bad); err == nil {
			t.Error("a malformed profile was accepted")
		}
	})

	t.Run("a missing profile is an error", func(t *testing.T) {
		if _, err := parseProfile(filepath.Join(dir, "absent.out")); err == nil {
			t.Error("a missing profile was accepted")
		}
	})
}

func TestWriteBadge(t *testing.T) {
	dir := t.TempDir()
	for _, tc := range []struct {
		name    string
		pct     float64
		minimum float64
		want    string
	}{
		{"at the target", 100, 100, `{"schemaVersion":1,"label":"coverage","message":"100.0%","color":"brightgreen"}`},
		{"below the gate", 97.5, 100, `{"schemaVersion":1,"label":"coverage","message":"97.5%","color":"red"}`},
		{"above a relaxed gate but short of the target", 97.5, 90,
			`{"schemaVersion":1,"label":"coverage","message":"97.5%","color":"yellow"}`},
	} {
		t.Run(tc.name, func(t *testing.T) {
			path := filepath.Join(dir, "badge.json")
			if err := writeBadge(path, tc.pct, tc.minimum); err != nil {
				t.Fatalf("unexpected error: %v", err)
			}
			got, err := os.ReadFile(path)
			if err != nil {
				t.Fatalf("read badge: %v", err)
			}
			if string(got) != tc.want+"\n" {
				t.Errorf("badge = %s, want %s", got, tc.want)
			}
		})
	}
}

func TestModuleFromGoMod(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "go.mod")
	write(t, path, "module example.com/m\n\ngo 1.27\n")

	got, err := moduleFromGoMod(path)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if got != "example.com/m" {
		t.Errorf("module = %q", got)
	}

	write(t, path, "go 1.27\n")
	if _, err := moduleFromGoMod(path); err == nil {
		t.Error("a go.mod without a module directive was accepted")
	}
	if _, err := moduleFromGoMod(filepath.Join(dir, "absent")); err == nil {
		t.Error("a missing go.mod was accepted")
	}
}

// A block with no statements is neither covered nor uncovered. An empty method
// body — the AFact of an analysis fact, for instance — produces one, and
// listing it as uncovered names a file that has nothing wrong with it.
func TestEmptyBlocksAreNeitherCoveredNorUncovered(t *testing.T) {
	total, covered, uncovered := summarise([]block{
		{file: "unitvet/unitvet.go", startLine: 112, statements: 0, count: 0},
		{file: "unitvet/unitvet.go", startLine: 114, statements: 1, count: 3},
		{file: "unitvet/check.go", startLine: 20, statements: 2, count: 0},
	})

	if total != 3 || covered != 1 {
		t.Errorf("counted %d of %d statements, want 1 of 3", covered, total)
	}
	if _, listed := uncovered["unitvet/unitvet.go"]; listed {
		t.Error("a file whose only uncovered block is empty was reported")
	}
	if got := len(uncovered["unitvet/check.go"]); got != 1 {
		t.Errorf("the genuinely uncovered block was reported %d times, want 1", got)
	}
}

func write(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}

// chdir moves into dir for the duration of the test: filter resolves file names
// relative to the module root, which is the working directory in CI.
func chdir(t *testing.T, dir string) {
	t.Helper()
	previous, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}
	if err := os.Chdir(dir); err != nil {
		t.Fatalf("chdir: %v", err)
	}
	t.Cleanup(func() {
		if err := os.Chdir(previous); err != nil {
			t.Fatalf("chdir back: %v", err)
		}
	})
}
