// Code generated by tools/catgen from catalog/catalog.yaml. DO NOT EDIT.

// Force, mass times acceleration.
package force

import (
	"github.com/timzifer/metrology"
	"github.com/timzifer/metrology/dimension"
	"github.com/timzifer/metrology/symbol"
)

// dim is the dimension every unit in this package measures.
var dim = dimension.New(dimension.Exponents{Time: -2, Length: 1, Mass: 1})

// Newton is the SI unit of force, kg·m·s⁻².
//
// Source: SI Brochure 9th ed., §2.3.4 Table 4
var Newton = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Symbol:    symbol.SI("N"),
})
