// Code generated by tools/catgen from the catalogue in catalog/. DO NOT EDIT.

// Force, mass times acceleration.
package force

import (
	"github.com/timzifer/metrology"
	"github.com/timzifer/metrology/dimension"
	"github.com/timzifer/metrology/symbol"
)

// dim is the dimension every unit in this package measures.
var dim = dimension.New(dimension.Exponents{Time: -2, Length: 1, Mass: 1})

// Newton is the SI unit of force, kg·m·s⁻².
//
// Source: SI Brochure 9th ed., §2.3.4 Table 4
var Newton = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Symbol:    symbol.SI("N"),
})

// Dyne is the CGS unit of force, a hundred-thousandth of a newton.
//
// Source: NIST SP 811 (2008), Appendix B.8
var Dyne = metrology.MustUnit(metrology.UnitDef{
	Dimension:   dim,
	Symbol:      symbol.Static("dyn"),
	Numerator:   "1",
	Denominator: "100000",
})
