// Code generated by tools/catgen from catalog/catalog.yaml. DO NOT EDIT.

// Electric potential difference.
package voltage

import (
	"github.com/timzifer/metrology"
	"github.com/timzifer/metrology/dimension"
	"github.com/timzifer/metrology/symbol"
)

// dim is the dimension every unit in this package measures.
var dim = dimension.New(dimension.Exponents{Time: -3, Length: 2, Mass: 1, ElectricCurrent: -1})

// Volt is the SI unit of electric potential difference, W·A⁻¹.
//
// Source: SI Brochure 9th ed., §2.3.4 Table 4
var Volt = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Symbol:    symbol.SI("V"),
})
