// Code generated by tools/catgen from the catalogue in catalog/. DO NOT EDIT.

// Dynamic viscosity, the resistance of a fluid to shear.
package viscosity

import (
	"github.com/timzifer/metrology"
	"github.com/timzifer/metrology/dimension"
	"github.com/timzifer/metrology/symbol"
)

// dim is the dimension every unit in this package measures.
var dim = dimension.New(dimension.Exponents{Time: -1, Length: -1, Mass: 1})

// PascalSecond is the SI unit of dynamic viscosity.
//
// Source: SI Brochure 9th ed., §2.3.4 Table 4
var PascalSecond = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Symbol:    symbol.Product(symbol.SI("Pa"), symbol.SI("s")),
})

// Poise is the CGS unit of dynamic viscosity, a tenth of a pascal second.
//
// Source: NIST SP 811 (2008), Appendix B.8
var Poise = metrology.MustUnit(metrology.UnitDef{
	Dimension:   dim,
	Symbol:      symbol.Static("P"),
	Numerator:   "1",
	Denominator: "10",
})
