// Code generated by tools/catgen from the catalogue in catalog/. DO NOT EDIT.

// Catalytic activity, substance converted per time.
package catalytic

import (
	"github.com/timzifer/metrology"
	"github.com/timzifer/metrology/dimension"
	"github.com/timzifer/metrology/symbol"
)

// dim is the dimension every unit in this package measures.
var dim = dimension.New(dimension.Exponents{Time: -1, AmountOfSubstance: 1})

// Katal is the SI unit of catalytic activity, mol·s⁻¹.
//
// Source: SI Brochure 9th ed., §2.3.4 Table 4
var Katal = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Symbol:    symbol.SI("kat"),
})
