// Code generated by tools/catgen from the catalogue in catalog/. DO NOT EDIT.

package unitvet

import (
	"github.com/timzifer/metrology"
	"github.com/timzifer/metrology/dimension"
)

// catalogue is every unit the library ships, keyed by the qualified name of
// the package-level variable holding it.
var catalogue = map[string]scale{
	"github.com/timzifer/metrology/units/current.Ampere":                          {dim: dimension.New(dimension.Exponents{ElectricCurrent: 1})},                                   // ampere
	"github.com/timzifer/metrology/units/length.Angstrom":                         {dim: dimension.New(dimension.Exponents{Length: 1})},                                            // angstrom
	"github.com/timzifer/metrology/units/area.Are":                                {dim: dimension.New(dimension.Exponents{Length: 2})},                                            // are
	"github.com/timzifer/metrology/units/pressure.Atmosphere":                     {dim: dimension.New(dimension.Exponents{Time: -2, Length: -1, Mass: 1})},                        // atmosphere
	"github.com/timzifer/metrology/units/pressure.Bar":                            {dim: dimension.New(dimension.Exponents{Time: -2, Length: -1, Mass: 1})},                        // bar
	"github.com/timzifer/metrology/units/area.Barn":                               {dim: dimension.New(dimension.Exponents{Length: 2})},                                            // barn
	"github.com/timzifer/metrology/units/activity.Becquerel":                      {dim: dimension.New(dimension.Exponents{Time: -1}), quantity: "radioactivity"},                  // becquerel
	"github.com/timzifer/metrology/units/energy.Calorie":                          {dim: dimension.New(dimension.Exponents{Time: -2, Length: 2, Mass: 1})},                         // calorie
	"github.com/timzifer/metrology/units/luminosity.Candela":                      {dim: dimension.New(dimension.Exponents{LuminousIntensity: 1}), quantity: "luminous intensity"}, // candela
	"github.com/timzifer/metrology/units/temperature.Celsius":                     {dim: dimension.New(dimension.Exponents{Temperature: 1}), kind: metrology.Absolute},             // celsius
	"github.com/timzifer/metrology/units/charge.Coulomb":                          {dim: dimension.New(dimension.Exponents{Time: 1, ElectricCurrent: 1})},                          // coulomb
	"github.com/timzifer/metrology/units/volume.CubicMetre":                       {dim: dimension.New(dimension.Exponents{Length: 3})},                                            // cubic_metre
	"github.com/timzifer/metrology/units/volumeflow.CubicMetrePerHour":            {dim: dimension.New(dimension.Exponents{Time: -1, Length: 3})},                                  // cubic_metre_per_hour
	"github.com/timzifer/metrology/units/volumeflow.CubicMetrePerSecond":          {dim: dimension.New(dimension.Exponents{Time: -1, Length: 3})},                                  // cubic_metre_per_second
	"github.com/timzifer/metrology/units/activity.Curie":                          {dim: dimension.New(dimension.Exponents{Time: -1}), quantity: "radioactivity"},                  // curie
	"github.com/timzifer/metrology/units/duration.Day":                            {dim: dimension.New(dimension.Exponents{Time: 1})},                                              // day
	"github.com/timzifer/metrology/units/force.Dyne":                              {dim: dimension.New(dimension.Exponents{Time: -2, Length: 1, Mass: 1})},                         // dyne
	"github.com/timzifer/metrology/units/energy.Electronvolt":                     {dim: dimension.New(dimension.Exponents{Time: -2, Length: 2, Mass: 1})},                         // electronvolt
	"github.com/timzifer/metrology/units/energy.Erg":                              {dim: dimension.New(dimension.Exponents{Time: -2, Length: 2, Mass: 1})},                         // erg
	"github.com/timzifer/metrology/units/temperature.Fahrenheit":                  {dim: dimension.New(dimension.Exponents{Temperature: 1}), kind: metrology.Absolute},             // fahrenheit
	"github.com/timzifer/metrology/units/capacitance.Farad":                       {dim: dimension.New(dimension.Exponents{Time: 4, Length: -2, Mass: -1, ElectricCurrent: 2})},    // farad
	"github.com/timzifer/metrology/units/imperial.Foot":                           {dim: dimension.New(dimension.Exponents{Length: 1})},                                            // foot
	"github.com/timzifer/metrology/units/fluxdensity.Gauss":                       {dim: dimension.New(dimension.Exponents{Time: -2, Mass: 1, ElectricCurrent: -1})},               // gauss
	"github.com/timzifer/metrology/units/density.GramPerLitre":                    {dim: dimension.New(dimension.Exponents{Length: -3, Mass: 1})},                                  // gram_per_litre
	"github.com/timzifer/metrology/units/absorbeddose.Gray":                       {dim: dimension.New(dimension.Exponents{Time: -2, Length: 2}), quantity: "absorbed dose"},       // gray
	"github.com/timzifer/metrology/units/area.Hectare":                            {dim: dimension.New(dimension.Exponents{Length: 2})},                                            // hectare
	"github.com/timzifer/metrology/units/inductance.Henry":                        {dim: dimension.New(dimension.Exponents{Time: -2, Length: 2, Mass: 1, ElectricCurrent: -2})},    // henry
	"github.com/timzifer/metrology/units/frequency.Hertz":                         {dim: dimension.New(dimension.Exponents{Time: -1}), quantity: "frequency"},                      // hertz
	"github.com/timzifer/metrology/units/duration.Hour":                           {dim: dimension.New(dimension.Exponents{Time: 1})},                                              // hour
	"github.com/timzifer/metrology/units/imperial.Inch":                           {dim: dimension.New(dimension.Exponents{Length: 1})},                                            // inch
	"github.com/timzifer/metrology/units/energy.Joule":                            {dim: dimension.New(dimension.Exponents{Time: -2, Length: 2, Mass: 1})},                         // joule
	"github.com/timzifer/metrology/units/specificheat.JoulePerKilogramKelvin":     {dim: dimension.New(dimension.Exponents{Time: -2, Length: 2, Temperature: -1})},                 // joule_per_kilogram_kelvin
	"github.com/timzifer/metrology/units/catalytic.Katal":                         {dim: dimension.New(dimension.Exponents{Time: -1, AmountOfSubstance: 1})},                       // katal
	"github.com/timzifer/metrology/units/temperature.Kelvin":                      {dim: dimension.New(dimension.Exponents{Temperature: 1}), kind: metrology.Absolute},             // kelvin
	"github.com/timzifer/metrology/units/interval.Kelvin":                         {dim: dimension.New(dimension.Exponents{Temperature: 1})},                                       // kelvin_interval
	"github.com/timzifer/metrology/units/mass.Kilogram":                           {dim: dimension.New(dimension.Exponents{Mass: 1})},                                              // kilogram
	"github.com/timzifer/metrology/units/density.KilogramPerCubicMetre":           {dim: dimension.New(dimension.Exponents{Length: -3, Mass: 1})},                                  // kilogram_per_cubic_metre
	"github.com/timzifer/metrology/units/massflow.KilogramPerHour":                {dim: dimension.New(dimension.Exponents{Time: -1, Mass: 1})},                                    // kilogram_per_hour
	"github.com/timzifer/metrology/units/massflow.KilogramPerSecond":              {dim: dimension.New(dimension.Exponents{Time: -1, Mass: 1})},                                    // kilogram_per_second
	"github.com/timzifer/metrology/units/length.Kilometre":                        {dim: dimension.New(dimension.Exponents{Length: 1})},                                            // kilometre
	"github.com/timzifer/metrology/units/velocity.KilometrePerHour":               {dim: dimension.New(dimension.Exponents{Time: -1, Length: 1})},                                  // kilometre_per_hour
	"github.com/timzifer/metrology/units/energy.KilowattHour":                     {dim: dimension.New(dimension.Exponents{Time: -2, Length: 2, Mass: 1})},                         // kilowatt_hour
	"github.com/timzifer/metrology/units/volume.Litre":                            {dim: dimension.New(dimension.Exponents{Length: 3})},                                            // litre
	"github.com/timzifer/metrology/units/volumeflow.LitrePerMinute":               {dim: dimension.New(dimension.Exponents{Time: -1, Length: 3})},                                  // litre_per_minute
	"github.com/timzifer/metrology/units/luminousflux.Lumen":                      {dim: dimension.New(dimension.Exponents{LuminousIntensity: 1}), quantity: "luminous flux"},      // lumen
	"github.com/timzifer/metrology/units/illuminance.Lux":                         {dim: dimension.New(dimension.Exponents{Length: -2, LuminousIntensity: 1})},                     // lux
	"github.com/timzifer/metrology/units/magneticflux.Maxwell":                    {dim: dimension.New(dimension.Exponents{Time: -2, Length: 2, Mass: 1, ElectricCurrent: -1})},    // maxwell
	"github.com/timzifer/metrology/units/length.Metre":                            {dim: dimension.New(dimension.Exponents{Length: 1})},                                            // metre
	"github.com/timzifer/metrology/units/velocity.MetrePerSecond":                 {dim: dimension.New(dimension.Exponents{Time: -1, Length: 1})},                                  // metre_per_second
	"github.com/timzifer/metrology/units/acceleration.MetrePerSecondSquared":      {dim: dimension.New(dimension.Exponents{Time: -2, Length: 1})},                                  // metre_per_second_squared
	"github.com/timzifer/metrology/units/imperial.Mile":                           {dim: dimension.New(dimension.Exponents{Length: 1})},                                            // mile
	"github.com/timzifer/metrology/units/pressure.MillimetreOfMercury":            {dim: dimension.New(dimension.Exponents{Time: -2, Length: -1, Mass: 1})},                        // millimetre_of_mercury
	"github.com/timzifer/metrology/units/pressure.MillimetreOfWater":              {dim: dimension.New(dimension.Exponents{Time: -2, Length: -1, Mass: 1})},                        // millimetre_of_water
	"github.com/timzifer/metrology/units/duration.Minute":                         {dim: dimension.New(dimension.Exponents{Time: 1})},                                              // minute
	"github.com/timzifer/metrology/units/substance.Mole":                          {dim: dimension.New(dimension.Exponents{AmountOfSubstance: 1})},                                 // mole
	"github.com/timzifer/metrology/units/concentration.MolePerCubicMetre":         {dim: dimension.New(dimension.Exponents{Length: -3, AmountOfSubstance: 1})},                     // mole_per_cubic_metre
	"github.com/timzifer/metrology/units/concentration.MolePerLitre":              {dim: dimension.New(dimension.Exponents{Length: -3, AmountOfSubstance: 1})},                     // mole_per_litre
	"github.com/timzifer/metrology/units/force.Newton":                            {dim: dimension.New(dimension.Exponents{Time: -2, Length: 1, Mass: 1})},                         // newton
	"github.com/timzifer/metrology/units/surfacetension.NewtonPerMetre":           {dim: dimension.New(dimension.Exponents{Time: -2, Mass: 1})},                                    // newton_per_metre
	"github.com/timzifer/metrology/units/resistance.Ohm":                          {dim: dimension.New(dimension.Exponents{Time: -3, Length: 2, Mass: 1, ElectricCurrent: -2})},    // ohm
	"github.com/timzifer/metrology/units/ratio.One":                               {dim: dimension.New(dimension.Exponents{})},                                                     // one
	"github.com/timzifer/metrology/units/imperial.Ounce":                          {dim: dimension.New(dimension.Exponents{Mass: 1})},                                              // ounce
	"github.com/timzifer/metrology/units/pressure.Pascal":                         {dim: dimension.New(dimension.Exponents{Time: -2, Length: -1, Mass: 1})},                        // pascal
	"github.com/timzifer/metrology/units/viscosity.PascalSecond":                  {dim: dimension.New(dimension.Exponents{Time: -1, Length: -1, Mass: 1})},                        // pascal_second
	"github.com/timzifer/metrology/units/ratio.Percent":                           {dim: dimension.New(dimension.Exponents{})},                                                     // percent
	"github.com/timzifer/metrology/units/ratio.PerMille":                          {dim: dimension.New(dimension.Exponents{})},                                                     // permille
	"github.com/timzifer/metrology/units/viscosity.Poise":                         {dim: dimension.New(dimension.Exponents{Time: -1, Length: -1, Mass: 1})},                        // poise
	"github.com/timzifer/metrology/units/imperial.Pound":                          {dim: dimension.New(dimension.Exponents{Mass: 1})},                                              // pound
	"github.com/timzifer/metrology/units/imperial.PoundForce":                     {dim: dimension.New(dimension.Exponents{Time: -2, Length: 1, Mass: 1})},                         // pound_force
	"github.com/timzifer/metrology/units/imperial.PoundPerSquareInch":             {dim: dimension.New(dimension.Exponents{Time: -2, Length: -1, Mass: 1})},                        // pound_per_square_inch
	"github.com/timzifer/metrology/units/ratio.PartsPerBillion":                   {dim: dimension.New(dimension.Exponents{})},                                                     // ppb
	"github.com/timzifer/metrology/units/ratio.PartsPerMillion":                   {dim: dimension.New(dimension.Exponents{})},                                                     // ppm
	"github.com/timzifer/metrology/units/angle.Radian":                            {dim: dimension.New(dimension.Exponents{}), quantity: "plane angle"},                            // radian
	"github.com/timzifer/metrology/units/interval.Rankine":                        {dim: dimension.New(dimension.Exponents{Temperature: 1})},                                       // rankine_interval
	"github.com/timzifer/metrology/units/dose.Rem":                                {dim: dimension.New(dimension.Exponents{Time: -2, Length: 2}), quantity: "dose equivalent"},     // rem
	"github.com/timzifer/metrology/units/duration.Second":                         {dim: dimension.New(dimension.Exponents{Time: 1})},                                              // second
	"github.com/timzifer/metrology/units/conductance.Siemens":                     {dim: dimension.New(dimension.Exponents{Time: 3, Length: -2, Mass: -1, ElectricCurrent: 2})},    // siemens
	"github.com/timzifer/metrology/units/dose.Sievert":                            {dim: dimension.New(dimension.Exponents{Time: -2, Length: 2}), quantity: "dose equivalent"},     // sievert
	"github.com/timzifer/metrology/units/area.SquareMetre":                        {dim: dimension.New(dimension.Exponents{Length: 2})},                                            // square_metre
	"github.com/timzifer/metrology/units/kinematicviscosity.SquareMetrePerSecond": {dim: dimension.New(dimension.Exponents{Time: -1, Length: 2}), quantity: "kinematic viscosity"}, // square_metre_per_second
	"github.com/timzifer/metrology/units/solidangle.Steradian":                    {dim: dimension.New(dimension.Exponents{}), quantity: "solid angle"},                            // steradian
	"github.com/timzifer/metrology/units/kinematicviscosity.Stokes":               {dim: dimension.New(dimension.Exponents{Time: -1, Length: 2}), quantity: "kinematic viscosity"}, // stokes
	"github.com/timzifer/metrology/units/fluxdensity.Tesla":                       {dim: dimension.New(dimension.Exponents{Time: -2, Mass: 1, ElectricCurrent: -1})},               // tesla
	"github.com/timzifer/metrology/units/mass.Tonne":                              {dim: dimension.New(dimension.Exponents{Mass: 1})},                                              // tonne
	"github.com/timzifer/metrology/units/pressure.Torr":                           {dim: dimension.New(dimension.Exponents{Time: -2, Length: -1, Mass: 1})},                        // torr
	"github.com/timzifer/metrology/units/voltage.Volt":                            {dim: dimension.New(dimension.Exponents{Time: -3, Length: 2, Mass: 1, ElectricCurrent: -1})},    // volt
	"github.com/timzifer/metrology/units/power.Watt":                              {dim: dimension.New(dimension.Exponents{Time: -3, Length: 2, Mass: 1})},                         // watt
	"github.com/timzifer/metrology/units/thermalconductivity.WattPerMetreKelvin":  {dim: dimension.New(dimension.Exponents{Time: -3, Length: 1, Mass: 1, Temperature: -1})},        // watt_per_metre_kelvin
	"github.com/timzifer/metrology/units/magneticflux.Weber":                      {dim: dimension.New(dimension.Exponents{Time: -2, Length: 2, Mass: 1, ElectricCurrent: -1})},    // weber
	"github.com/timzifer/metrology/units/imperial.Yard":                           {dim: dimension.New(dimension.Exponents{Length: 1})},                                            // yard
}
