// Code generated by tools/catgen from the catalogue in catalog/. DO NOT EDIT.

// Time, the SI base quantity.
//
// The package is not called time, because a program that measures durations
// usually imports the standard library package of that name as well.
package duration

import (
	"github.com/timzifer/metrology"
	"github.com/timzifer/metrology/dimension"
	"github.com/timzifer/metrology/symbol"
)

// dim is the dimension every unit in this package measures.
var dim = dimension.New(dimension.Exponents{Time: 1})

// Second is the SI base unit of time.
//
// Source: SI Brochure 9th ed., §2.3.1
var Second = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Symbol:    symbol.SI("s"),
})

// Minute is sixty seconds.
//
// Source: SI Brochure 9th ed., §4.1 Table 8
var Minute = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Symbol:    symbol.Static("min"),
	Numerator: "60",
})

// Hour is sixty minutes.
//
// Source: SI Brochure 9th ed., §4.1 Table 8
var Hour = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Symbol:    symbol.Static("h"),
	Numerator: "3600",
})

// Day is twenty-four hours.
//
// Source: SI Brochure 9th ed., §4.1 Table 8
var Day = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Symbol:    symbol.Static("d"),
	Numerator: "86400",
})
