// Code generated by tools/catgen from catalog/catalog.yaml. DO NOT EDIT.

package catalog

import (
	"github.com/timzifer/metrology"
	"github.com/timzifer/metrology/area"
	"github.com/timzifer/metrology/force"
	"github.com/timzifer/metrology/interval"
	"github.com/timzifer/metrology/length"
	"github.com/timzifer/metrology/pressure"
	"github.com/timzifer/metrology/temperature"
)

// all is every unit in the catalogue, ordered by catalogue id.
var all = []metrology.Unit{
	pressure.Bar,           // bar
	temperature.Celsius,    // celsius
	temperature.Fahrenheit, // fahrenheit
	temperature.Kelvin,     // kelvin
	interval.Kelvin,        // kelvin_interval
	length.Kilometre,       // kilometre
	length.Metre,           // metre
	force.Newton,           // newton
	pressure.Pascal,        // pascal
	interval.Rankine,       // rankine_interval
	area.SquareMetre,       // square_metre
	pressure.Torr,          // torr
}

// canonical maps a dimension and kind to the unit a result computed into
// that dimension is expressed in.
var canonical = map[key]metrology.Unit{
	{dim: temperature.Kelvin.Dimension(), kind: metrology.Absolute}: temperature.Kelvin,
	{dim: interval.Kelvin.Dimension(), kind: metrology.Interval}:    interval.Kelvin,
	{dim: length.Metre.Dimension(), kind: metrology.Interval}:       length.Metre,
	{dim: force.Newton.Dimension(), kind: metrology.Interval}:       force.Newton,
	{dim: pressure.Pascal.Dimension(), kind: metrology.Interval}:    pressure.Pascal,
	{dim: area.SquareMetre.Dimension(), kind: metrology.Interval}:   area.SquareMetre,
}

// bySymbol resolves the printed form of a unit back to the unit.
var bySymbol = map[symbolKey]metrology.Unit{
	{text: "bar", kind: metrology.Interval}:  pressure.Bar,
	{text: "°C", kind: metrology.Absolute}:   temperature.Celsius,
	{text: "°F", kind: metrology.Absolute}:   temperature.Fahrenheit,
	{text: "K", kind: metrology.Absolute}:    temperature.Kelvin,
	{text: "K", kind: metrology.Interval}:    interval.Kelvin,
	{text: "km", kind: metrology.Interval}:   length.Kilometre,
	{text: "m", kind: metrology.Interval}:    length.Metre,
	{text: "N", kind: metrology.Interval}:    force.Newton,
	{text: "Pa", kind: metrology.Interval}:   pressure.Pascal,
	{text: "°R", kind: metrology.Interval}:   interval.Rankine,
	{text: "m²", kind: metrology.Interval}:   area.SquareMetre,
	{text: "Torr", kind: metrology.Interval}: pressure.Torr,
}
