// Code generated by tools/catgen from the catalogue in catalog/. DO NOT EDIT.

// Pressure, force per area.
package pressure

import (
	"github.com/timzifer/metrology"
	"github.com/timzifer/metrology/dimension"
	"github.com/timzifer/metrology/symbol"
)

// dim is the dimension every unit in this package measures.
var dim = dimension.New(dimension.Exponents{Time: -2, Length: -1, Mass: 1})

// Pascal is the SI unit of pressure, N·m⁻².
//
// Source: SI Brochure 9th ed., §2.3.4 Table 4
var Pascal = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Symbol:    symbol.SI("Pa"),
})

// Bar is exactly 100 kPa.
//
// Source: SI Brochure 9th ed., §4.1 Table 8
var Bar = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Symbol:    symbol.Static("bar"),
	Numerator: "100000",
})

// Atmosphere is the standard atmosphere, 101325 Pa by definition.
//
// Source: NIST SP 811 (2008), Appendix B.8
var Atmosphere = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Symbol:    symbol.Static("atm"),
	Numerator: "101325",
})

// Torr is one 760th of the standard atmosphere.
//
// Source: NIST SP 811 (2008), Appendix B.8
var Torr = metrology.MustUnit(metrology.UnitDef{
	Dimension:   dim,
	Symbol:      symbol.Static("Torr"),
	Numerator:   "101325",
	Denominator: "760",
})

// MillimetreOfMercury is the conventional millimetre of mercury, as used in blood pressure.
//
// Source: NIST SP 811 (2008), Appendix B.8
var MillimetreOfMercury = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Symbol:    symbol.Static("mmHg"),
	Numerator: "133.322387415",
})

// MillimetreOfWater is the conventional millimetre of water, as used for draught and filter pressure.
//
// Source: NIST SP 811 (2008), Appendix B.8
var MillimetreOfWater = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Symbol:    symbol.Static("mmH₂O"),
	Numerator: "9.80665",
})
