// Code generated by tools/catgen from catalog/catalog.yaml. DO NOT EDIT.

// Volume flow rate, the quantity a flow meter reads.
package volumeflow

import (
	"github.com/timzifer/metrology"
	"github.com/timzifer/metrology/dimension"
	"github.com/timzifer/metrology/symbol"
)

// dim is the dimension every unit in this package measures.
var dim = dimension.New(dimension.Exponents{Time: -1, Length: 3})

// CubicMetrePerSecond is the SI unit of volume flow rate.
//
// Source: SI Brochure 9th ed., §2.3.4 Table 3
var CubicMetrePerSecond = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Symbol:    symbol.Quotient(symbol.SIPow("m", 3), symbol.SI("s")),
})

// CubicMetrePerHour is the unit most industrial flow meters are scaled in.
//
// Source: NIST SP 811 (2008), Appendix B.9
var CubicMetrePerHour = metrology.MustUnit(metrology.UnitDef{
	Dimension:   dim,
	Symbol:      symbol.Static("m³/h"),
	Numerator:   "1",
	Denominator: "3600",
})

// LitrePerMinute is the unit small flow meters are scaled in.
//
// Source: NIST SP 811 (2008), Appendix B.9
var LitrePerMinute = metrology.MustUnit(metrology.UnitDef{
	Dimension:   dim,
	Symbol:      symbol.Static("L/min"),
	Numerator:   "1",
	Denominator: "60000",
})
