// Code generated by tools/catgen from catalog/catalog.yaml. DO NOT EDIT.

// Dose equivalent: absorbed dose weighted by the biological effect of the
// radiation.
package dose

import (
	"github.com/timzifer/metrology"
	"github.com/timzifer/metrology/dimension"
	"github.com/timzifer/metrology/symbol"
)

// dim is the dimension every unit in this package measures.
var dim = dimension.New(dimension.Exponents{Time: -2, Length: 2})

// Quantity is what every unit in this package measures, where the
// dimension alone does not say it: dose equivalent.
//
// It is a reserved name of this catalogue (D6, D16) and the spelling a caller
// should compare against — a string literal of the same words is a second
// spelling of one fact, with nothing to keep the two in step.
const Quantity metrology.Quantity = "dose equivalent"

// Sievert is the SI unit of dose equivalent, J·kg⁻¹.
//
// Source: SI Brochure 9th ed., §2.3.4 Table 4
var Sievert = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Quantity:  Quantity,
	Symbol:    symbol.SI("Sv"),
})

// Rem is the older unit of dose equivalent, a hundredth of a sievert.
//
// Source: NIST SP 811 (2008), Appendix B.8
var Rem = metrology.MustUnit(metrology.UnitDef{
	Dimension:   dim,
	Quantity:    Quantity,
	Symbol:      symbol.Static("rem"),
	Numerator:   "1",
	Denominator: "100",
})
