// Code generated by tools/catgen from the catalogue in catalog/. DO NOT EDIT.

// Luminous intensity: radiant power in a direction, weighted by the response
// of the eye.
//
// It shares its dimension with luminous flux — the steradian is
// dimensionless — which is why both carry a quantity tag (D6).
package luminosity

import (
	"github.com/timzifer/metrology"
	"github.com/timzifer/metrology/dimension"
	"github.com/timzifer/metrology/symbol"
)

// dim is the dimension every unit in this package measures.
var dim = dimension.New(dimension.Exponents{LuminousIntensity: 1})

// Quantity is what every unit in this package measures, where the
// dimension alone does not say it: luminous intensity.
//
// It is a reserved name of this catalogue (D6, D16) and the spelling a caller
// should compare against — a string literal of the same words is a second
// spelling of one fact, with nothing to keep the two in step.
const Quantity metrology.Quantity = "luminous intensity"

// Candela is the SI base unit of luminous intensity.
//
// Source: SI Brochure 9th ed., §2.3.1
var Candela = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Quantity:  Quantity,
	Symbol:    symbol.SI("cd"),
})
