// Code generated by tools/catgen from catalog/catalog.yaml. DO NOT EDIT.

// Mass density, mass per volume.
package density

import (
	"github.com/timzifer/metrology"
	"github.com/timzifer/metrology/dimension"
	"github.com/timzifer/metrology/symbol"
)

// dim is the dimension every unit in this package measures.
var dim = dimension.New(dimension.Exponents{Length: -3, Mass: 1})

// KilogramPerCubicMetre is the SI unit of mass density.
//
// Source: SI Brochure 9th ed., §2.3.4 Table 3
var KilogramPerCubicMetre = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Symbol:    symbol.Quotient(symbol.Gram(), symbol.SIPow("m", 3)),
})

// GramPerLitre is a gram in a litre, which is also a kilogram in a cubic metre.
//
// Source: NIST SP 811 (2008), Appendix B.9
var GramPerLitre = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Symbol:    symbol.Static("g/L"),
})
