// Code generated by tools/catgen from the catalogue in catalog/. DO NOT EDIT.

// Magnetic field strength, H: the field a current produces, as distinct from
// the flux density B that the field produces in a material.
//
// The oersted is 1000/4π amperes per metre, so its entry carries a π
// exponent of −1 (D20) — the mirror image of the degree, which carries one
// of +1. What a degree multiplies by, an oersted divides by.
package fieldstrength

import (
	"github.com/timzifer/metrology"
	"github.com/timzifer/metrology/dimension"
	"github.com/timzifer/metrology/symbol"
)

// dim is the dimension every unit in this package measures.
var dim = dimension.New(dimension.Exponents{Length: -1, ElectricCurrent: 1})

// AmperePerMetre is the SI unit of magnetic field strength.
//
// Source: SI Brochure 9th ed., §2.3.4 Table 3
var AmperePerMetre = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Symbol:    symbol.Quotient(symbol.SI("A"), symbol.SI("m")),
})

// Oersted is the CGS unit of magnetic field strength, 1000/4π amperes per metre.
//
// Source: NIST SP 811 (2008), Appendix B.8
var Oersted = metrology.MustUnit(metrology.UnitDef{
	Dimension:   dim,
	Symbol:      symbol.Static("Oe"),
	Numerator:   "1000",
	Denominator: "4",
	Pi:          -1,
})
