// Code generated by tools/catgen from catalog/catalog.yaml. DO NOT EDIT.

// Frequency: how often a periodic event repeats.
//
// T⁻¹ is also the dimension of radioactivity, and a becquerel is not a
// hertz. The tag is what keeps them apart (D6).
package frequency

import (
	"github.com/timzifer/metrology"
	"github.com/timzifer/metrology/dimension"
	"github.com/timzifer/metrology/symbol"
)

// dim is the dimension every unit in this package measures.
var dim = dimension.New(dimension.Exponents{Time: -1})

// Quantity is what every unit in this package measures, where the
// dimension alone does not say it: frequency.
//
// It is a reserved name of this catalogue (D6, D16) and the spelling a caller
// should compare against — a string literal of the same words is a second
// spelling of one fact, with nothing to keep the two in step.
const Quantity metrology.Quantity = "frequency"

// Hertz is one cycle per second.
//
// Source: SI Brochure 9th ed., §2.3.4 Table 4
var Hertz = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Quantity:  Quantity,
	Symbol:    symbol.SI("Hz"),
})
