// Code generated by tools/catgen from catalog/catalog.yaml. DO NOT EDIT.

// Luminous flux: luminous intensity over a solid angle.
//
// The steradian is dimensionless, so a lumen has the dimension of a candela
// and the tag is what distinguishes them (D6).
package luminousflux

import (
	"github.com/timzifer/metrology"
	"github.com/timzifer/metrology/dimension"
	"github.com/timzifer/metrology/symbol"
)

// dim is the dimension every unit in this package measures.
var dim = dimension.New(dimension.Exponents{LuminousIntensity: 1})

// Lumen is the SI unit of luminous flux, cd·sr.
//
// Source: SI Brochure 9th ed., §2.3.4 Table 4
var Lumen = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Quantity:  "luminous flux",
	Symbol:    symbol.SI("lm"),
})
