// Code generated by tools/catgen from the catalogue in catalog/. DO NOT EDIT.

// Electric charge.
package charge

import (
	"github.com/timzifer/metrology"
	"github.com/timzifer/metrology/dimension"
	"github.com/timzifer/metrology/symbol"
)

// dim is the dimension every unit in this package measures.
var dim = dimension.New(dimension.Exponents{Time: 1, ElectricCurrent: 1})

// Coulomb is the SI unit of electric charge, A·s.
//
// Source: SI Brochure 9th ed., §2.3.4 Table 4
var Coulomb = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Symbol:    symbol.SI("C"),
})
