// Code generated by tools/catgen from the catalogue in catalog/. DO NOT EDIT.

// Mass, the SI base quantity of inertia.
package mass

import (
	"github.com/timzifer/metrology"
	"github.com/timzifer/metrology/dimension"
	"github.com/timzifer/metrology/symbol"
)

// dim is the dimension every unit in this package measures.
var dim = dimension.New(dimension.Exponents{Mass: 1})

// Kilogram is the SI base unit of mass, and the one whose name already carries a prefix.
//
// Source: SI Brochure 9th ed., §2.3.1
var Kilogram = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Symbol:    symbol.Gram(),
})

// Tonne is a thousand kilograms.
//
// Source: SI Brochure 9th ed., §4.1 Table 8
var Tonne = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Symbol:    symbol.Static("t"),
	Numerator: "1000",
})
