// Code generated by tools/catgen from the catalogue in catalog/. DO NOT EDIT.

// Dimensionless ratios: a number that came from dividing like by like.
//
// A ratio has no dimension, which is exactly why it needs saying: 5 % and
// 5 ppm are the same dimension and not the same number.
package ratio

import (
	"github.com/timzifer/metrology"
	"github.com/timzifer/metrology/dimension"
	"github.com/timzifer/metrology/symbol"
)

// dim is the dimension every unit in this package measures.
var dim = dimension.New(dimension.Exponents{})

// One is the dimensionless unit, a bare number.
//
// Source: SI Brochure 9th ed., §2.3.3
var One = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Symbol:    symbol.Static("1"),
})

// Percent is one part in a hundred.
//
// Source: SI Brochure 9th ed., §5.4.7
var Percent = metrology.MustUnit(metrology.UnitDef{
	Dimension:   dim,
	Symbol:      symbol.Static("%"),
	Numerator:   "1",
	Denominator: "100",
})

// PerMille is one part in a thousand.
//
// Source: SI Brochure 9th ed., §5.4.7
var PerMille = metrology.MustUnit(metrology.UnitDef{
	Dimension:   dim,
	Symbol:      symbol.Static("‰"),
	Numerator:   "1",
	Denominator: "1000",
})

// PartsPerMillion is one part in a million, as used for trace concentrations.
//
// Source: SI Brochure 9th ed., §5.4.7 (which advises naming the quantity instead)
var PartsPerMillion = metrology.MustUnit(metrology.UnitDef{
	Dimension:   dim,
	Symbol:      symbol.Static("ppm"),
	Numerator:   "1",
	Denominator: "1000000",
})

// PartsPerBillion is one part in a thousand million.
//
// Source: SI Brochure 9th ed., §5.4.7 (which advises naming the quantity instead)
var PartsPerBillion = metrology.MustUnit(metrology.UnitDef{
	Dimension:   dim,
	Symbol:      symbol.Static("ppb"),
	Numerator:   "1",
	Denominator: "1000000000",
})
