// Code generated by tools/catgen from the catalogue in catalog/. DO NOT EDIT.

// Package us holds the customary units of the United States that differ
// from the imperial ones of the same name.
//
// Its counterpart is units/customary/imperial. The two are separate
// packages so that us.Gallon and imperial.Gallon are two names rather than
// one aliased twice, and the units they agree on are in the parent (D19).
//
// None of these carries the bare spelling. "gal" names a US gallon in one
// country and an imperial gallon a fifth larger in another, so it names no
// unit here: the text form of D12 is a canonical form only where a symbol
// resolves to one unit, and refusing an ambiguous spelling is better than
// reading it back as the wrong one (O3). The spellings that are used
// instead — galUS, flozUS, tonUS — are this library's, because no standard
// supplies one.
package us

import (
	"github.com/timzifer/metrology"
	"github.com/timzifer/metrology/dimension"
	"github.com/timzifer/metrology/symbol"
)

// Gallon is the US liquid gallon, 231 cubic inches, exactly 3.785411784 litres.
//
// Source: NIST SP 811 (2008), Appendix B.6
var Gallon = metrology.MustUnit(metrology.UnitDef{
	Dimension:   dimension.New(dimension.Exponents{Length: 3}),
	Symbol:      symbol.Static("galUS"),
	Numerator:   "3785411784",
	Denominator: "1000000000000",
})

// FluidOunce is a hundred-and-twenty-eighth of a US gallon.
//
// Source: NIST SP 811 (2008), Appendix B.6
var FluidOunce = metrology.MustUnit(metrology.UnitDef{
	Dimension:   dimension.New(dimension.Exponents{Length: 3}),
	Symbol:      symbol.Static("flozUS"),
	Numerator:   "3785411784",
	Denominator: "128000000000000",
})

// Ton is the short ton, two thousand pounds, exactly 907.18474 kilograms.
//
// Source: NIST SP 811 (2008), Appendix B.6
var Ton = metrology.MustUnit(metrology.UnitDef{
	Dimension:   dimension.New(dimension.Exponents{Mass: 1}),
	Symbol:      symbol.Static("tonUS"),
	Numerator:   "90718474",
	Denominator: "100000",
})
