// Code generated by tools/catgen from catalog/catalog.yaml. DO NOT EDIT.

// Surface tension, force per length of contact line.
package surfacetension

import (
	"github.com/timzifer/metrology"
	"github.com/timzifer/metrology/dimension"
	"github.com/timzifer/metrology/symbol"
)

// dim is the dimension every unit in this package measures.
var dim = dimension.New(dimension.Exponents{Time: -2, Mass: 1})

// NewtonPerMetre is the SI unit of surface tension.
//
// Source: SI Brochure 9th ed., §2.3.4 Table 3
var NewtonPerMetre = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Symbol:    symbol.Quotient(symbol.SI("N"), symbol.SI("m")),
})
