// Code generated by tools/catgen from catalog/catalog.yaml. DO NOT EDIT.

// Luminous intensity: radiant power in a direction, weighted by the response
// of the eye.
//
// It shares its dimension with luminous flux — the steradian is
// dimensionless — which is why both carry a quantity tag (D6).
package luminosity

import (
	"github.com/timzifer/metrology"
	"github.com/timzifer/metrology/dimension"
	"github.com/timzifer/metrology/symbol"
)

// dim is the dimension every unit in this package measures.
var dim = dimension.New(dimension.Exponents{LuminousIntensity: 1})

// Candela is the SI base unit of luminous intensity.
//
// Source: SI Brochure 9th ed., §2.3.1
var Candela = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Quantity:  "luminous intensity",
	Symbol:    symbol.SI("cd"),
})
