// Code generated by tools/catgen from catalog/catalog.yaml. DO NOT EDIT.

// Plane angle.
//
// An angle is a ratio of two lengths and therefore dimensionless, which is
// why it carries a quantity tag: without one, an angle and a bare number
// would be the same thing to the arithmetic (D6).
//
// The degree of arc is not here. It is π/180 radians, and π has no exact
// decimal fraction — a rounded factor in this catalogue would be exactly
// what D4 forbids.
package angle

import (
	"github.com/timzifer/metrology"
	"github.com/timzifer/metrology/dimension"
	"github.com/timzifer/metrology/symbol"
)

// dim is the dimension every unit in this package measures.
var dim = dimension.New(dimension.Exponents{})

// Radian is the SI unit of plane angle.
//
// Source: SI Brochure 9th ed., §2.3.4 Table 4
var Radian = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Quantity:  "plane angle",
	Symbol:    symbol.Static("rad"),
})
