// Code generated by tools/catgen from the catalogue in catalog/. DO NOT EDIT.

// Kinematic viscosity: dynamic viscosity over density.
//
// L²T⁻¹ is also the dimension of thermal diffusivity and of a diffusion
// coefficient. Those are not in the catalogue, because they would print the
// same symbol — m²/s — and the text form of D12 has to read back to one
// unit. See section 8 of CONCEPT.md.
package kinematicviscosity

import (
	"github.com/timzifer/metrology"
	"github.com/timzifer/metrology/dimension"
	"github.com/timzifer/metrology/symbol"
)

// dim is the dimension every unit in this package measures.
var dim = dimension.New(dimension.Exponents{Time: -1, Length: 2})

// Quantity is what every unit in this package measures, where the
// dimension alone does not say it: kinematic viscosity.
//
// It is a reserved name of this catalogue (D6, D16) and the spelling a caller
// should compare against — a string literal of the same words is a second
// spelling of one fact, with nothing to keep the two in step.
const Quantity metrology.Quantity = "kinematic viscosity"

// SquareMetrePerSecond is the SI unit of kinematic viscosity.
//
// Source: SI Brochure 9th ed., §2.3.4 Table 3
var SquareMetrePerSecond = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Quantity:  Quantity,
	Symbol:    symbol.Quotient(symbol.SIPow("m", 2), symbol.SI("s")),
})

// Stokes is the CGS unit of kinematic viscosity.
//
// Source: NIST SP 811 (2008), Appendix B.8
var Stokes = metrology.MustUnit(metrology.UnitDef{
	Dimension:   dim,
	Quantity:    Quantity,
	Symbol:      symbol.Static("St"),
	Numerator:   "1",
	Denominator: "10000",
})
