// Code generated by tools/catgen from catalog/catalog.yaml. DO NOT EDIT.

// Amount-of-substance concentration.
package concentration

import (
	"github.com/timzifer/metrology"
	"github.com/timzifer/metrology/dimension"
	"github.com/timzifer/metrology/symbol"
)

// dim is the dimension every unit in this package measures.
var dim = dimension.New(dimension.Exponents{Length: -3, AmountOfSubstance: 1})

// MolePerCubicMetre is the SI unit of concentration.
//
// Source: SI Brochure 9th ed., §2.3.4 Table 3
var MolePerCubicMetre = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Symbol:    symbol.Quotient(symbol.SI("mol"), symbol.SIPow("m", 3)),
})

// MolePerLitre is the molar, a mole in a litre.
//
// Source: NIST SP 811 (2008), Appendix B.9
var MolePerLitre = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Symbol:    symbol.Static("mol/L"),
	Numerator: "1000",
})
