// Code generated by tools/catgen from the catalogue in catalog/. DO NOT EDIT.

// Amount of substance, counted in entities rather than measured.
package substance

import (
	"github.com/timzifer/metrology"
	"github.com/timzifer/metrology/dimension"
	"github.com/timzifer/metrology/symbol"
)

// dim is the dimension every unit in this package measures.
var dim = dimension.New(dimension.Exponents{AmountOfSubstance: 1})

// Mole is the SI base unit of amount of substance.
//
// Source: SI Brochure 9th ed., §2.3.1
var Mole = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Symbol:    symbol.SI("mol"),
})
