// Code generated by tools/catgen from the catalogue in catalog/. DO NOT EDIT.

// Energy, work and heat.
//
// L²MT⁻² is also the dimension of a torque, which the SI does not give a
// name of its own: a newton metre of torque and a joule of energy are
// written differently on purpose.
package energy

import (
	"github.com/timzifer/metrology"
	"github.com/timzifer/metrology/dimension"
	"github.com/timzifer/metrology/symbol"
)

// dim is the dimension every unit in this package measures.
var dim = dimension.New(dimension.Exponents{Time: -2, Length: 2, Mass: 1})

// Joule is the SI unit of energy, N·m.
//
// Source: SI Brochure 9th ed., §2.3.4 Table 4
var Joule = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Symbol:    symbol.SI("J"),
})

// KilowattHour is a kilowatt for an hour, the unit an electricity meter counts in.
//
// Source: NIST SP 811 (2008), Appendix B.8
var KilowattHour = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Symbol:    symbol.Static("kWh"),
	Numerator: "3600000",
})

// Calorie is the international table calorie, exactly 4.1868 J.
//
// Source: NIST SP 811 (2008), Appendix B.8
var Calorie = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Symbol:    symbol.Static("cal"),
	Numerator: "4.1868",
})

// Electronvolt is the energy an electron gains across one volt.
//
// Source: SI Brochure 9th ed., §4.1 Table 7
var Electronvolt = metrology.MustUnit(metrology.UnitDef{
	Dimension:   dim,
	Symbol:      symbol.SI("eV"),
	Numerator:   "1.602176634",
	Denominator: "10000000000000000000",
})

// Erg is the CGS unit of energy, a ten-millionth of a joule.
//
// Source: NIST SP 811 (2008), Appendix B.8
var Erg = metrology.MustUnit(metrology.UnitDef{
	Dimension:   dim,
	Symbol:      symbol.Static("erg"),
	Numerator:   "1",
	Denominator: "10000000",
})
