// Code generated by tools/catgen from the catalogue in catalog/. DO NOT EDIT.

// Electric current, the SI base quantity of charge flow.
package current

import (
	"github.com/timzifer/metrology"
	"github.com/timzifer/metrology/dimension"
	"github.com/timzifer/metrology/symbol"
)

// dim is the dimension every unit in this package measures.
var dim = dimension.New(dimension.Exponents{ElectricCurrent: 1})

// Ampere is the SI base unit of electric current.
//
// Source: SI Brochure 9th ed., §2.3.1
var Ampere = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Symbol:    symbol.SI("A"),
})
