// Code generated by tools/catgen from the catalogue in catalog/. DO NOT EDIT.

// Length, the SI base quantity of extent.
package length

import (
	"github.com/timzifer/metrology"
	"github.com/timzifer/metrology/dimension"
	"github.com/timzifer/metrology/symbol"
)

// dim is the dimension every unit in this package measures.
var dim = dimension.New(dimension.Exponents{Length: 1})

// Metre is the SI base unit of length.
//
// Source: SI Brochure 9th ed., §2.3.1
var Metre = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Symbol:    symbol.SI("m"),
})

// Kilometre is a thousand metres.
//
// Source: SI Brochure 9th ed., §3 (SI prefixes)
var Kilometre = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Symbol:    symbol.Static("km"),
	Numerator: "1000",
})

// Angstrom is a ten-billionth of a metre, the scale of an atomic radius.
//
// Source: NIST SP 811 (2008), Appendix B.8
var Angstrom = metrology.MustUnit(metrology.UnitDef{
	Dimension:   dim,
	Symbol:      symbol.Static("Å"),
	Numerator:   "1",
	Denominator: "10000000000",
})
