// Code generated by tools/catgen from the catalogue in catalog/. DO NOT EDIT.

// Length, the SI base quantity of extent.
//
// The parsec is the one unit here whose factor is not rational: it is
// 648000/π astronomical units by definition, so the entry carries a π
// exponent (D20) and 648000 · 149 597 870 700 as its numerator. The
// astronomical unit is exact, and is here because the parsec is defined
// against it.
package length

import (
	"github.com/timzifer/metrology"
	"github.com/timzifer/metrology/dimension"
	"github.com/timzifer/metrology/symbol"
)

// dim is the dimension every unit in this package measures.
var dim = dimension.New(dimension.Exponents{Length: 1})

// Metre is the SI base unit of length.
//
// Source: SI Brochure 9th ed., §2.3.1
var Metre = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Symbol:    symbol.SI("m"),
})

// Kilometre is a thousand metres.
//
// Source: SI Brochure 9th ed., §3 (SI prefixes)
var Kilometre = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Symbol:    symbol.Static("km"),
	Numerator: "1000",
})

// Angstrom is a ten-billionth of a metre, the scale of an atomic radius.
//
// Source: NIST SP 811 (2008), Appendix B.8
var Angstrom = metrology.MustUnit(metrology.UnitDef{
	Dimension:   dim,
	Symbol:      symbol.Static("Å"),
	Numerator:   "1",
	Denominator: "10000000000",
})

// AstronomicalUnit is 149 597 870 700 metres exactly, a defined length since the IAU fixed it in 2012.
//
// Source: SI Brochure 9th ed., §4.1 Table 8
var AstronomicalUnit = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Symbol:    symbol.Static("au"),
	Numerator: "149597870700",
})

// Parsec is the distance at which one astronomical unit subtends one arcsecond, 648000/π au.
//
// Source: IAU 2015 Resolution B2; NIST SP 811 (2008), Appendix B.8 gives 3.085 678 E+16 m
var Parsec = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Symbol:    symbol.SI("pc"),
	Numerator: "96939420213600000",
	Pi:        -1,
})
