// Code generated by tools/catgen from catalog/catalog.yaml. DO NOT EDIT.

// Solid angle: the two-dimensional counterpart of the radian, and equally
// dimensionless.
package solidangle

import (
	"github.com/timzifer/metrology"
	"github.com/timzifer/metrology/dimension"
	"github.com/timzifer/metrology/symbol"
)

// dim is the dimension every unit in this package measures.
var dim = dimension.New(dimension.Exponents{})

// Quantity is what every unit in this package measures, where the
// dimension alone does not say it: solid angle.
//
// It is a reserved name of this catalogue (D6, D16) and the spelling a caller
// should compare against — a string literal of the same words is a second
// spelling of one fact, with nothing to keep the two in step.
const Quantity metrology.Quantity = "solid angle"

// Steradian is the SI unit of solid angle.
//
// Source: SI Brochure 9th ed., §2.3.4 Table 4
var Steradian = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Quantity:  Quantity,
	Symbol:    symbol.Static("sr"),
})
