// Code generated by tools/catgen from the catalogue in catalog/. DO NOT EDIT.

// Thermal conductivity, heat flow per length and temperature difference.
package thermalconductivity

import (
	"github.com/timzifer/metrology"
	"github.com/timzifer/metrology/dimension"
	"github.com/timzifer/metrology/symbol"
)

// dim is the dimension every unit in this package measures.
var dim = dimension.New(dimension.Exponents{Time: -3, Length: 1, Mass: 1, Temperature: -1})

// WattPerMetreKelvin is the SI unit of thermal conductivity.
//
// Source: SI Brochure 9th ed., §2.3.4 Table 3
var WattPerMetreKelvin = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Symbol:    symbol.Quotient(symbol.SI("W"), symbol.Product(symbol.SI("m"), symbol.SI("K"))),
})
