// Code generated by tools/catgen from catalog/catalog.yaml. DO NOT EDIT.

// Specific heat capacity, heat per mass and temperature difference.
package specificheat

import (
	"github.com/timzifer/metrology"
	"github.com/timzifer/metrology/dimension"
	"github.com/timzifer/metrology/symbol"
)

// dim is the dimension every unit in this package measures.
var dim = dimension.New(dimension.Exponents{Time: -2, Length: 2, Temperature: -1})

// JoulePerKilogramKelvin is the SI unit of specific heat capacity.
//
// Source: SI Brochure 9th ed., §2.3.4 Table 3
var JoulePerKilogramKelvin = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Symbol:    symbol.Quotient(symbol.SI("J"), symbol.Product(symbol.Gram(), symbol.SI("K"))),
})
