// Code generated by tools/catgen from the catalogue in catalog/. DO NOT EDIT.

// Mass flow rate.
package massflow

import (
	"github.com/timzifer/metrology"
	"github.com/timzifer/metrology/dimension"
	"github.com/timzifer/metrology/symbol"
)

// dim is the dimension every unit in this package measures.
var dim = dimension.New(dimension.Exponents{Time: -1, Mass: 1})

// KilogramPerSecond is the SI unit of mass flow rate.
//
// Source: SI Brochure 9th ed., §2.3.4 Table 3
var KilogramPerSecond = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Symbol:    symbol.Quotient(symbol.Gram(), symbol.SI("s")),
})

// KilogramPerHour is mass flow as a plant reads it.
//
// Source: NIST SP 811 (2008), Appendix B.9
var KilogramPerHour = metrology.MustUnit(metrology.UnitDef{
	Dimension:   dim,
	Symbol:      symbol.Static("kg/h"),
	Numerator:   "1",
	Denominator: "3600",
})
