// Code generated by tools/catgen from the catalogue in catalog/. DO NOT EDIT.

// Acceleration, velocity per time.
package acceleration

import (
	"github.com/timzifer/metrology"
	"github.com/timzifer/metrology/dimension"
	"github.com/timzifer/metrology/symbol"
)

// dim is the dimension every unit in this package measures.
var dim = dimension.New(dimension.Exponents{Time: -2, Length: 1})

// MetrePerSecondSquared is the SI unit of acceleration.
//
// Source: SI Brochure 9th ed., §2.3.4 Table 3
var MetrePerSecondSquared = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Symbol:    symbol.Quotient(symbol.SI("m"), symbol.SIPow("s", 2)),
})
