// Code generated by tools/catgen from the catalogue in catalog/. DO NOT EDIT.

// Power, energy per time.
package power

import (
	"github.com/timzifer/metrology"
	"github.com/timzifer/metrology/dimension"
	"github.com/timzifer/metrology/symbol"
)

// dim is the dimension every unit in this package measures.
var dim = dimension.New(dimension.Exponents{Time: -3, Length: 2, Mass: 1})

// Watt is the SI unit of power, J·s⁻¹.
//
// Source: SI Brochure 9th ed., §2.3.4 Table 4
var Watt = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Symbol:    symbol.SI("W"),
})
