// Code generated by tools/catgen from catalog/catalog.yaml. DO NOT EDIT.

// Solid angle: the two-dimensional counterpart of the radian, and equally
// dimensionless.
package solidangle

import (
	"github.com/timzifer/metrology"
	"github.com/timzifer/metrology/dimension"
	"github.com/timzifer/metrology/symbol"
)

// dim is the dimension every unit in this package measures.
var dim = dimension.New(dimension.Exponents{})

// Steradian is the SI unit of solid angle.
//
// Source: SI Brochure 9th ed., §2.3.4 Table 4
var Steradian = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Quantity:  "solid angle",
	Symbol:    symbol.Static("sr"),
})
