// Code generated by tools/catgen from the catalogue in catalog/. DO NOT EDIT.

// Package customary holds the units the two customary systems agree on —
// the foot, the pound, the pound-force, the pound per square inch.
//
// Where they disagree, the unit is in customary/us or customary/imperial
// instead: the gallons differ by a fifth, and a package that held both
// under one name would be a name contradicting a definition (D19).
//
// It is the one generated package grouped by provenance rather than by
// quantity (D19), so its units are on several dimensions and it declares no
// dimension of its own. What they have in common is that they are not SI and
// not among the non-SI units accepted for use with the SI: those — the bar,
// the torr, the ångström — are in the quantity packages beside the units
// they belong with, because NIST SP 811 Appendix B.8 sanctions them and this
// catalogue audits against it.
//
// Every factor here is exact. The international yard and pound agreement of
// 1959 defines the inch as exactly 25.4 mm and the pound as exactly
// 0.45359237 kg, and the rest follow from those by exact multiplication.
package customary

import (
	"github.com/timzifer/metrology"
	"github.com/timzifer/metrology/dimension"
	"github.com/timzifer/metrology/symbol"
)

// Inch is exactly 25.4 millimetres, by the international agreement of 1959.
//
// Source: NIST SP 811 (2008), Appendix B.6
var Inch = metrology.MustUnit(metrology.UnitDef{
	Dimension:   dimension.New(dimension.Exponents{Length: 1}),
	Symbol:      symbol.Static("in"),
	Numerator:   "254",
	Denominator: "10000",
})

// Foot is twelve inches, exactly 0.3048 metres.
//
// Source: NIST SP 811 (2008), Appendix B.6
var Foot = metrology.MustUnit(metrology.UnitDef{
	Dimension:   dimension.New(dimension.Exponents{Length: 1}),
	Symbol:      symbol.Static("ft"),
	Numerator:   "3048",
	Denominator: "10000",
})

// Yard is three feet, exactly 0.9144 metres.
//
// Source: NIST SP 811 (2008), Appendix B.6
var Yard = metrology.MustUnit(metrology.UnitDef{
	Dimension:   dimension.New(dimension.Exponents{Length: 1}),
	Symbol:      symbol.Static("yd"),
	Numerator:   "9144",
	Denominator: "10000",
})

// Mile is the statute mile, 5280 feet, exactly 1609.344 metres.
//
// Source: NIST SP 811 (2008), Appendix B.6
var Mile = metrology.MustUnit(metrology.UnitDef{
	Dimension:   dimension.New(dimension.Exponents{Length: 1}),
	Symbol:      symbol.Static("mi"),
	Numerator:   "1609344",
	Denominator: "1000",
})

// Pound is the avoirdupois pound, exactly 0.45359237 kilograms.
//
// Source: NIST SP 811 (2008), Appendix B.6
var Pound = metrology.MustUnit(metrology.UnitDef{
	Dimension:   dimension.New(dimension.Exponents{Mass: 1}),
	Symbol:      symbol.Static("lb"),
	Numerator:   "45359237",
	Denominator: "100000000",
})

// Ounce is the avoirdupois ounce, a sixteenth of a pound.
//
// Source: NIST SP 811 (2008), Appendix B.6
var Ounce = metrology.MustUnit(metrology.UnitDef{
	Dimension:   dimension.New(dimension.Exponents{Mass: 1}),
	Symbol:      symbol.Static("oz"),
	Numerator:   "45359237",
	Denominator: "1600000000",
})

// PoundForce is the force a pound exerts under standard gravity, exactly 4.4482216152605 newtons — a different dimension from the pound of mass, and therefore a different unit.
//
// Source: NIST SP 811 (2008), Appendix B.6
var PoundForce = metrology.MustUnit(metrology.UnitDef{
	Dimension:   dimension.New(dimension.Exponents{Time: -2, Length: 1, Mass: 1}),
	Symbol:      symbol.Static("lbf"),
	Numerator:   "44482216152605",
	Denominator: "10000000000000",
})

// PoundPerSquareInch is one pound-force on a square inch — the quotient is no finite decimal, which is what the exact fraction of D4 is for.
//
// Source: NIST SP 811 (2008), Appendix B.6
var PoundPerSquareInch = metrology.MustUnit(metrology.UnitDef{
	Dimension:   dimension.New(dimension.Exponents{Time: -2, Length: -1, Mass: 1}),
	Symbol:      symbol.Static("psi"),
	Numerator:   "4.4482216152605",
	Denominator: "0.00064516",
})
