// Code generated by tools/catgen from the catalogue in catalog/. DO NOT EDIT.

// Magnetic flux.
package magneticflux

import (
	"github.com/timzifer/metrology"
	"github.com/timzifer/metrology/dimension"
	"github.com/timzifer/metrology/symbol"
)

// dim is the dimension every unit in this package measures.
var dim = dimension.New(dimension.Exponents{Time: -2, Length: 2, Mass: 1, ElectricCurrent: -1})

// Weber is the SI unit of magnetic flux, V·s.
//
// Source: SI Brochure 9th ed., §2.3.4 Table 4
var Weber = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Symbol:    symbol.SI("Wb"),
})

// Maxwell is the CGS unit of magnetic flux.
//
// Source: NIST SP 811 (2008), Appendix B.8
var Maxwell = metrology.MustUnit(metrology.UnitDef{
	Dimension:   dim,
	Symbol:      symbol.Static("Mx"),
	Numerator:   "1",
	Denominator: "100000000",
})
