// Code generated by tools/catgen from catalog/catalog.yaml. DO NOT EDIT.

// Area, length squared.
package area

import (
	"github.com/timzifer/metrology"
	"github.com/timzifer/metrology/dimension"
	"github.com/timzifer/metrology/symbol"
)

// dim is the dimension every unit in this package measures.
var dim = dimension.New(dimension.Exponents{Length: 2})

// SquareMetre is the SI unit of area.
//
// Source: SI Brochure 9th ed., §2.3.4 Table 3
var SquareMetre = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Symbol:    symbol.SIPow("m", 2),
})
