// Code generated by tools/catgen from catalog/catalog.yaml. DO NOT EDIT.

// Radioactivity: nuclear decays per second.
//
// Same dimension as frequency, different quantity — the SI names both
// because counting decays and counting cycles are not the same measurement.
package activity

import (
	"github.com/timzifer/metrology"
	"github.com/timzifer/metrology/dimension"
	"github.com/timzifer/metrology/symbol"
)

// dim is the dimension every unit in this package measures.
var dim = dimension.New(dimension.Exponents{Time: -1})

// Becquerel is one nuclear decay per second.
//
// Source: SI Brochure 9th ed., §2.3.4 Table 4
var Becquerel = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Quantity:  "radioactivity",
	Symbol:    symbol.SI("Bq"),
})

// Curie is 37 thousand million decays per second, the activity of a gram of radium.
//
// Source: NIST SP 811 (2008), Appendix B.8
var Curie = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Quantity:  "radioactivity",
	Symbol:    symbol.Static("Ci"),
	Numerator: "37000000000",
})
