// Code generated by tools/catgen from catalog/catalog.yaml. DO NOT EDIT.

// Absorbed dose: energy deposited per mass of tissue.
//
// Same dimension as dose equivalent, and deliberately a different quantity:
// the gray measures what was deposited, the sievert what it does to a body.
// Reporting one as the other is the mistake this tag exists to prevent.
package absorbeddose

import (
	"github.com/timzifer/metrology"
	"github.com/timzifer/metrology/dimension"
	"github.com/timzifer/metrology/symbol"
)

// dim is the dimension every unit in this package measures.
var dim = dimension.New(dimension.Exponents{Time: -2, Length: 2})

// Quantity is what every unit in this package measures, where the
// dimension alone does not say it: absorbed dose.
//
// It is a reserved name of this catalogue (D6, D16) and the spelling a caller
// should compare against — a string literal of the same words is a second
// spelling of one fact, with nothing to keep the two in step.
const Quantity metrology.Quantity = "absorbed dose"

// Gray is the SI unit of absorbed dose, J·kg⁻¹.
//
// Source: SI Brochure 9th ed., §2.3.4 Table 4
var Gray = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Quantity:  Quantity,
	Symbol:    symbol.SI("Gy"),
})
