// Code generated by tools/catgen from catalog/catalog.yaml. DO NOT EDIT.

// Interval units: the scales differences are read on.
//
// 25 °C − 20 °C is 5 K, not 5 °C. The difference between two points on an
// affine scale is a span along it, and a span belongs to a scale with no
// offset (D6). These are the units those spans are expressed in.
package interval

import (
	"github.com/timzifer/metrology"
	"github.com/timzifer/metrology/dimension"
	"github.com/timzifer/metrology/symbol"
)

// dim is the dimension every unit in this package measures.
var dim = dimension.New(dimension.Exponents{Temperature: 1})

// Kelvin is a temperature difference of one kelvin.
//
// Source: SI Brochure 9th ed., §2.3.1
var Kelvin = metrology.MustUnit(metrology.UnitDef{
	Dimension: dim,
	Symbol:    symbol.SI("K"),
})

// Rankine is a temperature difference of one degree Rankine, five ninths of a kelvin.
//
// Source: NIST SP 811 (2008), Appendix B.8
var Rankine = metrology.MustUnit(metrology.UnitDef{
	Dimension:   dim,
	Symbol:      symbol.Static("°R"),
	Numerator:   "5",
	Denominator: "9",
})
